# version: '3.8'

services:
  authentication:
    build: ./backend/authentication
    container_name: ft_authentication
    restart: always
    ports:
      - "8001:8001"
    networks:
      - ft_network
    env_file:
      - ./backend/authentication/.env
    volumes:
      - ./backend/authentication:/app
      - auth_node_modules:/app/node_modules
      - auth_data:/app/data  # Persistent storage for authentication database

  notifications:
    build: ./backend/notifications
    container_name: ft_notifications
    restart: always
    ports:
      - "8000:8000"
    networks:
      - ft_network
    volumes:
      - ./backend/notifications:/app
      - notifications_node_modules:/app/node_modules
      - notifications_data:/app/data  # Persistent storage for notifications database
    depends_on:
      - authentication

  chat:
    build: ./backend/chat
    container_name: ft_chat
    restart: always
    ports:
      - "3002:3002"
    networks:
      - ft_network
    env_file:
      - ./backend/chat/.env
    volumes:
      - ./backend/chat:/app
      - chat_node_modules:/app/node_modules
      - chat_data:/app/data  # Persistent storage for chat database
    depends_on:
      - authentication

  frontend:
    build: ./frontend
    container_name: ft_frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - ft_network
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - authentication
      - chat
      - notifications

networks:
  ft_network:
    driver: bridge

volumes:
  auth_data:
  notifications_data:
  chat_data:
  auth_node_modules:
  notifications_node_modules:
  chat_node_modules:
  frontend_node_modules:
