# version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ft_backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - ft_network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data  # Persistent storage for SQLite database file
  frontend:
    build: ./frontend
    container_name: ft_frontend
    restart: always
    ports:
      - "1234:1234"
    networks:
      - ft_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend


networks:
  ft_network:
    driver: bridge

volumes:
  data:
