version: '3.8'

services:
  pong-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped